on:
  workflow_dispatch:
  pull_request:
name: "Build"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build MathlibManual
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build Mathlib Manual
        uses: leanprover/lean-action@v1
        with:
          build-args: "MathlibManual"
